### ISSUE TITLE
需要增加对apache的支持

### ISSUE THREAD

**Issue by mikelei8291** [hanzexu990323/lnmp-chacha20#12]
<s>Apache哭啦</s>

**Comment by BakaChinatsu** [comment]
诶，Apache支持CHACHA20了么？

**Comment by mikelei8291** [comment]
诶？Apache原来不支持CHACHA20啊。。

**Comment by mikelei8291** [comment]
好像是支持的啊？

**Comment by BakaChinatsu** [comment]
在Apache下，LibreSSL会导致 mod_ssl 出错，所以如果想在Apache下实现CHACHA20的话只能使用openssl 的 aead 分支,但这个分支并不适合在生产环境中使用_(:3」∠)_

http://stackoverflow.com/questions/31368436/implement-chacha20-poly1305-in-openssl-on-windows

https://www.futures.moe/writings/chacha20-poly1305.htm

https://www.v2ex.com/t/174625

**Comment by mikelei8291** [comment]
好，那就等OpenSSL更新再说吧
