### ISSUE TITLE
差不多可以发布下一个版本了？

### ISSUE THREAD

**Issue by BakaChinatsu** [hanzexu990323/lnmp-chacha20#21]
CentOS求测试喵qwq

**Comment by mikelei8291** [comment]
嗯，可以发布新版本了
不过你安装的时候都是 `git clone` 完再把这些文件覆盖到lnmp安装包源文件上再执行 `./install.sh` 的？
不过这个覆盖的步骤有些麻烦啊，要不要再写一个覆盖文件的脚本呢？

**Comment by BakaChinatsu** [comment]
吼啊！但是怎麼寫呢喵？

**Comment by mikelei8291** [comment]
我待会写一个好了

**Comment by mikelei8291** [comment]
突然发现其实一行代码就能解决问题了，是我太baka了😂

`cd lnmp-chacha20 && cp -af * ~/lnmp1.2 && cd ~/lnmp1.2`
<s>`echo Mike is a baka!`</s>

**Comment by mikelei8291** [comment]
New version [`v0.2.0-beta`](https://github.com/hanzexu990323/lnmp-chacha20/releases/tag/v0.2.0-beta) released after commit 836fc93

**Comment by mikelei8291** [comment]
2015-12-02: CentOS 6 x64 Test **Passed**

**Comment by mikelei8291** [comment]
Latest **stable version** [`v0.2.1`](https://github.com/hanzexu990323/lnmp-chacha20/releases/tag/v0.2.1) released after commit bfb5b33 with latest test result.
