### ISSUE TITLE
使用～而非/root?

### ISSUE THREAD

**Issue by zhangyubaka** [hanzexu990323/lnmp-chacha20#22]
感觉用root的话sudo用户会不方便?

**Comment by BakaChinatsu** [comment]
用sudo可以運行喵？
<code>if [ $(id -u) != "0" ]; then
    echo "Error: You must be root to run this script, please use root to install lnmp"
    exit 1
fi</code>

**Comment by zhangyubaka** [comment]
![image](https://cloud.githubusercontent.com/assets/7823161/11596344/2fbaf966-9a7a-11e5-938c-1bfa7e95c8ce.png)
应当可行

**Comment by zhangyubaka** [comment]
![image](https://cloud.githubusercontent.com/assets/7823161/11596440/ad1cb1ce-9a7a-11e5-9301-d76c9b2e8419.png)

**Comment by BakaChinatsu** [comment]
那個...乃說的那段代碼在哪裡😂

**Comment by zhangyubaka** [comment]
qwq!在结尾处

**Comment by BakaChinatsu** [comment]
天哪，这个iss窝到现在才理解是什么意思= =||
但是sudo应该是完全取得root的权限和root的工作环境的啊，那么主目录应该也会变成 /root 才对？

**Comment by zhangyubaka** [comment]
不，sudo 中一些变量是继承的
雨宮千夏 notifications@github.com于2016年10月9日 周日上午10:58写道：

**Comment by BakaChinatsu** [comment]
酱
