### ISSUE TITLE
考虑整合一下Let’s Encrypt？

### ISSUE THREAD

**Issue by BakaChinatsu** [hanzexu990323/lnmp-chacha20#24]
看到Let’s Encrypt已经进入正式运行阶段了，要不要与Let’s Encrypt的自动颁发证书程序整合一下呢？

**Comment by mikelei8291** [comment]
感觉不是很必要诶。。
毕竟Let's Encrypt的配置也就一条命令的事，Let's Encrypt那边已经很自动了
不过要整合也不是不可以w
