### ISSUE TITLE
需要增加对yum系的支持

### ISSUE THREAD

**Issue by BakaChinatsu** [hanzexu990323/lnmp-chacha20#8]
如题，目前的依赖是通过apt-get安装的，需要在lnmp脚本里增加自动判断系统类型并安装依赖

**Comment by mikelei8291** [comment]
我去试着添加一下

**Comment by BakaChinatsu** [comment]
麻烦乃了，话说突然想起来之前测试一直失败貌似是Ubuntu 15.10的锅orz

**Comment by mikelei8291** [comment]
具体原因呢？不过Ubuntu 15.10也不是推荐使用的版本。。
<s>所以不支持也没问题吧（逃</s>

**Comment by BakaChinatsu** [comment]
不清楚qwq 提示pagespeed的参数有问题_(:з」∠)_

总之一样的脚本换到14.04就正常了233333

**Comment by mikelei8291** [comment]
这些组件都是编译安装的，不用添加额外的支持啦~
